### ISSUE TITLE
Zombie "Subscribe to newsletter" banner flashes on refresh

### ISSUE THREAD

**Issue by ESRogs** [Discordius/Telescope#15]
After you click the 'x' on "Subscribe to newsletter" it remembers that you don't want to see the banner anymore. But every time you refresh, you see the banner briefly before it disappears again.

**Comment by Discordius** [comment]
This is related to the ominous server side rendering stuff that is happening. 

Is there any reason not just to deactivate the newsletter?

**Comment by ESRogs** [comment]
Fixed with https://github.com/Discordius/Telescope/commit/221b2041ee75ec49c54ab3d9e3dc087775ec2c49
